on:
  push:
    branches:
      - main

name: Build and Release Apps
jobs:
  build-mac-android-web-etc:
    name: Build Apps
    runs-on: macos-latest
    steps:
      - name: Export Release Timestamp
        run: echo "APP_VERSION=v$(date +'%Y.%m.%d.%H.%m.%S')" >> $GITHUB_ENV
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Install pub Dependencies
        run: flutter pub get
      - name: Run Tests
        run: flutter test
      - name: Build Android App
        run: flutter build apk --split-per-abi
      - name: Build iOS App
        run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
      - name: Build Web App
        run: |
          flutter build web
          cd build/web
          zip -r web-app.zip .
          cd ../..

      - name: Enable Macos
        run: flutter config --enable-macos-desktop
      - name: Build macOS app
        run: flutter build macos --release
      - name: Zip up macOS app
        run: |
          pwd
          ls -l
          ls -R build/macos/Build/Products/
          # cd build/macos/Build/Products/Debug
          cd build/macos/Build/Products/Release
          zip -r macos-app.zip flutter_ghactions
          cd ../../../../..
          pwd
          # zip -r macos-app.zip build/macos

      - name: Release Apps
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.APP_VERSION }}
          name: ${{ env.APP_VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: 'build/app/outputs/apk/release/*.apk,build/web/web-app.zip,build/ios/iphoneos/app.ipa,build/macos/Build/Products/Release/macos-app.zip'

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Export Release Timestamp
        shell: bash
        run: echo "APP_VERSION=v$(date +'%Y.%m.%d.%H.%m.%S')" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
      - run: flutter config --enable-windows-desktop
      - run: flutter pub get
      - run: flutter build windows --release
      - name: Zip up windows app
        run: |
          pwd
          ls -l build/windows
          ls -l build/windows/runner
          cd build/windows/runner/Release
          zip -r windows-app.zip .
          cd ../../../..
          pwd
      - name: Release Windows App
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.APP_VERSION }}
          name: ${{ env.APP_VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: 'build/windows/runner/Release/windows-app.zip'
